### ISSUE TITLE
Exception on PL/SQL Developer start

### ISSUE THREAD

**Issue by Tichij** [Starina123/rrPLDPlugin#1]
Hi, I always get an exception on PLSD start (see attached pic).
Additional info:
Windows 10 Enterprise 21H1 x64,
PLSD ver. 15.0.2.2054 x64 (installed in user\AppData\Local\Programs\, because of lack of admin rights),
rrProject ver. 2.3.2.

![Capture](https://user-images.githubusercontent.com/14314531/183825652-4d1de43d-c42c-4b06-b968-2a122fc396b4.PNG)

**Comment by Starina123** [comment]
@Tichij 

If you have administrator rights, then you can run the executable from the plugin folder, which will register the protocol URL (`rrPLDUrlHandler reg`). Alternative way disable tool "Url Link assistant"

The bug will be fix.
