### ISSUE TITLE
Быстрый поиск. Элементы обозревателя объектов. Нет данных

### ISSUE THREAD

**Issue by derevyov** [Starina123/rrPLDPlugin#3]
Сразу после подключения к базе данных при попытке вызвать "Быстрый поиск. Элементы обозревателя объектов" получаю ошибку "Данных не найдено".
После раскрытия в Обозревателе объектов папки с любыми объектами, например с таблицами, появляется быстрый поиск по таблицам, если открываю пакеты, то добавляется поиск по пакетам.
Это баг или фича? :)

**Comment by Starina123** [comment]
Так и задумано поиск осуществляется в отображаемых элементах второго
уровня.

чт, 9 мар. 2023 г., 17:35 derevyov ***@***.***>:
